# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VentanaPrincipal.ui',
# licensing of '.\VentanaPrincipal.ui' applies.
#
# Created: Wed Jul 17 21:04:08 2019
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(900, 638)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.principalTab = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.principalTab.setPalette(palette)
        self.principalTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.principalTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.principalTab.setElideMode(QtCore.Qt.ElideNone)
        self.principalTab.setDocumentMode(True)
        self.principalTab.setTabsClosable(False)
        self.principalTab.setTabBarAutoHide(True)
        self.principalTab.setObjectName("principalTab")
        self.analisisTab = QtWidgets.QWidget()
        self.analisisTab.setObjectName("analisisTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.analisisTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AnalisisstackedWidget = QtWidgets.QStackedWidget(self.analisisTab)
        self.AnalisisstackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnalisisstackedWidget.sizePolicy().hasHeightForWidth())
        self.AnalisisstackedWidget.setSizePolicy(sizePolicy)
        self.AnalisisstackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AnalisisstackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AnalisisstackedWidget.setObjectName("AnalisisstackedWidget")
        self.tf = QtWidgets.QWidget()
        self.tf.setObjectName("tf")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tf)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tfLabel1 = QtWidgets.QLabel(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfLabel1.sizePolicy().hasHeightForWidth())
        self.tfLabel1.setSizePolicy(sizePolicy)
        self.tfLabel1.setObjectName("tfLabel1")
        self.gridLayout_9.addWidget(self.tfLabel1, 1, 0, 1, 2)
        self.tfdatosTextEdit1 = QtWidgets.QPlainTextEdit(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdatosTextEdit1.sizePolicy().hasHeightForWidth())
        self.tfdatosTextEdit1.setSizePolicy(sizePolicy)
        self.tfdatosTextEdit1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tfdatosTextEdit1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tfdatosTextEdit1.setReadOnly(True)
        self.tfdatosTextEdit1.setPlainText("")
        self.tfdatosTextEdit1.setBackgroundVisible(True)
        self.tfdatosTextEdit1.setObjectName("tfdatosTextEdit1")
        self.gridLayout_9.addWidget(self.tfdatosTextEdit1, 5, 1, 1, 1)
        self.tfcalcButton1 = QtWidgets.QPushButton(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfcalcButton1.sizePolicy().hasHeightForWidth())
        self.tfcalcButton1.setSizePolicy(sizePolicy)
        self.tfcalcButton1.setObjectName("tfcalcButton1")
        self.gridLayout_9.addWidget(self.tfcalcButton1, 6, 1, 1, 1)
        self.demLabel1 = QtWidgets.QLabel(self.tf)
        self.demLabel1.setObjectName("demLabel1")
        self.gridLayout_9.addWidget(self.demLabel1, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 7, 1, 1, 1)
        self.numLabel1 = QtWidgets.QLabel(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLabel1.sizePolicy().hasHeightForWidth())
        self.numLabel1.setSizePolicy(sizePolicy)
        self.numLabel1.setObjectName("numLabel1")
        self.gridLayout_9.addWidget(self.numLabel1, 2, 0, 1, 1)
        self.tfdatosLabel1 = QtWidgets.QLabel(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdatosLabel1.sizePolicy().hasHeightForWidth())
        self.tfdatosLabel1.setSizePolicy(sizePolicy)
        self.tfdatosLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tfdatosLabel1.setScaledContents(False)
        self.tfdatosLabel1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tfdatosLabel1.setWordWrap(False)
        self.tfdatosLabel1.setObjectName("tfdatosLabel1")
        self.gridLayout_9.addWidget(self.tfdatosLabel1, 5, 0, 1, 1)
        self.tfnumEdit1 = QtWidgets.QLineEdit(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfnumEdit1.sizePolicy().hasHeightForWidth())
        self.tfnumEdit1.setSizePolicy(sizePolicy)
        self.tfnumEdit1.setObjectName("tfnumEdit1")
        self.gridLayout_9.addWidget(self.tfnumEdit1, 2, 1, 1, 1)
        self.tfdemEdit1 = QtWidgets.QLineEdit(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdemEdit1.sizePolicy().hasHeightForWidth())
        self.tfdemEdit1.setSizePolicy(sizePolicy)
        self.tfdemEdit1.setObjectName("tfdemEdit1")
        self.gridLayout_9.addWidget(self.tfdemEdit1, 3, 1, 1, 1)
        self.tfperiodoEdit1 = QtWidgets.QLineEdit(self.tf)
        self.tfperiodoEdit1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfperiodoEdit1.sizePolicy().hasHeightForWidth())
        self.tfperiodoEdit1.setSizePolicy(sizePolicy)
        self.tfperiodoEdit1.setInputMask("")
        self.tfperiodoEdit1.setText("")
        self.tfperiodoEdit1.setObjectName("tfperiodoEdit1")
        self.gridLayout_9.addWidget(self.tfperiodoEdit1, 4, 1, 1, 1)
        self.tfdiscretocheckBox1 = QtWidgets.QCheckBox(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdiscretocheckBox1.sizePolicy().hasHeightForWidth())
        self.tfdiscretocheckBox1.setSizePolicy(sizePolicy)
        self.tfdiscretocheckBox1.setObjectName("tfdiscretocheckBox1")
        self.gridLayout_9.addWidget(self.tfdiscretocheckBox1, 4, 0, 1, 1)
        self.AnalisisstackedWidget.addWidget(self.tf)
        self.ss = QtWidgets.QWidget()
        self.ss.setObjectName("ss")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.ss)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.ssALabel1 = QtWidgets.QLabel(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssALabel1.sizePolicy().hasHeightForWidth())
        self.ssALabel1.setSizePolicy(sizePolicy)
        self.ssALabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssALabel1.setObjectName("ssALabel1")
        self.gridLayout_11.addWidget(self.ssALabel1, 1, 0, 1, 1)
        self.ssAEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssAEdit1.sizePolicy().hasHeightForWidth())
        self.ssAEdit1.setSizePolicy(sizePolicy)
        self.ssAEdit1.setObjectName("ssAEdit1")
        self.gridLayout_11.addWidget(self.ssAEdit1, 1, 1, 1, 1)
        self.ssBLabel1 = QtWidgets.QLabel(self.ss)
        self.ssBLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssBLabel1.setObjectName("ssBLabel1")
        self.gridLayout_11.addWidget(self.ssBLabel1, 2, 0, 1, 1)
        self.ssBEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssBEdit1.sizePolicy().hasHeightForWidth())
        self.ssBEdit1.setSizePolicy(sizePolicy)
        self.ssBEdit1.setObjectName("ssBEdit1")
        self.gridLayout_11.addWidget(self.ssBEdit1, 2, 1, 1, 1)
        self.sscalcButton1 = QtWidgets.QPushButton(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sscalcButton1.sizePolicy().hasHeightForWidth())
        self.sscalcButton1.setSizePolicy(sizePolicy)
        self.sscalcButton1.setObjectName("sscalcButton1")
        self.gridLayout_11.addWidget(self.sscalcButton1, 7, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 8, 1, 1, 1)
        self.ssdatosLabel1 = QtWidgets.QLabel(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosLabel1.sizePolicy().hasHeightForWidth())
        self.ssdatosLabel1.setSizePolicy(sizePolicy)
        self.ssdatosLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssdatosLabel1.setScaledContents(False)
        self.ssdatosLabel1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssdatosLabel1.setWordWrap(False)
        self.ssdatosLabel1.setObjectName("ssdatosLabel1")
        self.gridLayout_11.addWidget(self.ssdatosLabel1, 6, 0, 1, 1)
        self.ssLabel1 = QtWidgets.QLabel(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssLabel1.sizePolicy().hasHeightForWidth())
        self.ssLabel1.setSizePolicy(sizePolicy)
        self.ssLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssLabel1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssLabel1.setWordWrap(False)
        self.ssLabel1.setObjectName("ssLabel1")
        self.gridLayout_11.addWidget(self.ssLabel1, 0, 0, 1, 2)
        self.ssperiodoEdit1 = QtWidgets.QLineEdit(self.ss)
        self.ssperiodoEdit1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssperiodoEdit1.sizePolicy().hasHeightForWidth())
        self.ssperiodoEdit1.setSizePolicy(sizePolicy)
        self.ssperiodoEdit1.setInputMask("")
        self.ssperiodoEdit1.setText("")
        self.ssperiodoEdit1.setObjectName("ssperiodoEdit1")
        self.gridLayout_11.addWidget(self.ssperiodoEdit1, 5, 1, 1, 1)
        self.ssdatosTextEdit1 = QtWidgets.QPlainTextEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosTextEdit1.sizePolicy().hasHeightForWidth())
        self.ssdatosTextEdit1.setSizePolicy(sizePolicy)
        self.ssdatosTextEdit1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ssdatosTextEdit1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ssdatosTextEdit1.setReadOnly(True)
        self.ssdatosTextEdit1.setPlainText("")
        self.ssdatosTextEdit1.setBackgroundVisible(True)
        self.ssdatosTextEdit1.setObjectName("ssdatosTextEdit1")
        self.gridLayout_11.addWidget(self.ssdatosTextEdit1, 6, 1, 1, 1)
        self.ssdiscretocheckBox1 = QtWidgets.QCheckBox(self.ss)
        self.ssdiscretocheckBox1.setObjectName("ssdiscretocheckBox1")
        self.gridLayout_11.addWidget(self.ssdiscretocheckBox1, 5, 0, 1, 1)
        self.ssCEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssCEdit1.sizePolicy().hasHeightForWidth())
        self.ssCEdit1.setSizePolicy(sizePolicy)
        self.ssCEdit1.setObjectName("ssCEdit1")
        self.gridLayout_11.addWidget(self.ssCEdit1, 3, 1, 1, 1)
        self.ssDEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssDEdit1.sizePolicy().hasHeightForWidth())
        self.ssDEdit1.setSizePolicy(sizePolicy)
        self.ssDEdit1.setObjectName("ssDEdit1")
        self.gridLayout_11.addWidget(self.ssDEdit1, 4, 1, 1, 1)
        self.ssCLabel1 = QtWidgets.QLabel(self.ss)
        self.ssCLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssCLabel1.setObjectName("ssCLabel1")
        self.gridLayout_11.addWidget(self.ssCLabel1, 3, 0, 1, 1)
        self.ssDLabel1 = QtWidgets.QLabel(self.ss)
        self.ssDLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssDLabel1.setObjectName("ssDLabel1")
        self.gridLayout_11.addWidget(self.ssDLabel1, 4, 0, 1, 1)
        self.AnalisisstackedWidget.addWidget(self.ss)
        self.gridLayout_3.addWidget(self.AnalisisstackedWidget, 1, 1, 1, 1)
        self.analisisGraficaTab = QtWidgets.QTabWidget(self.analisisTab)
        self.analisisGraficaTab.setAutoFillBackground(True)
        self.analisisGraficaTab.setDocumentMode(False)
        self.analisisGraficaTab.setMovable(True)
        self.analisisGraficaTab.setTabBarAutoHide(False)
        self.analisisGraficaTab.setObjectName("analisisGraficaTab")
        self.stepTab = QtWidgets.QWidget()
        self.stepTab.setObjectName("stepTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stepTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stepGraphicsView1 = MlpWidget(self.stepTab)
        self.stepGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stepGraphicsView1.setInteractive(True)
        self.stepGraphicsView1.setObjectName("stepGraphicsView1")
        self.gridLayout_2.addWidget(self.stepGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.stepTab, "")
        self.impulseTab = QtWidgets.QWidget()
        self.impulseTab.setObjectName("impulseTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.impulseTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.impulseGraphicsView1 = MlpWidget(self.impulseTab)
        self.impulseGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.impulseGraphicsView1.setObjectName("impulseGraphicsView1")
        self.gridLayout_4.addWidget(self.impulseGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.impulseTab, "")
        self.bodeTab = QtWidgets.QWidget()
        self.bodeTab.setObjectName("bodeTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bodeTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.BodeGraphicsView1 = MlpWidgetSubplot(self.bodeTab)
        self.BodeGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BodeGraphicsView1.setObjectName("BodeGraphicsView1")
        self.gridLayout_5.addWidget(self.BodeGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.bodeTab, "")
        self.nyquistTab = QtWidgets.QWidget()
        self.nyquistTab.setObjectName("nyquistTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.nyquistTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.NyquistGraphicsView1 = MlpWidget(self.nyquistTab)
        self.NyquistGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.NyquistGraphicsView1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NyquistGraphicsView1.setObjectName("NyquistGraphicsView1")
        self.gridLayout_6.addWidget(self.NyquistGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.nyquistTab, "")
        self.rlocusTab = QtWidgets.QWidget()
        self.rlocusTab.setObjectName("rlocusTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.rlocusTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.rlocusGraphicsView1 = MlpWidget(self.rlocusTab)
        self.rlocusGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rlocusGraphicsView1.setObjectName("rlocusGraphicsView1")
        self.gridLayout_7.addWidget(self.rlocusGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.rlocusTab, "")
        self.gridLayout_3.addWidget(self.analisisGraficaTab, 0, 3, 8, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.analisisTab)
        self.groupBox1.setTitle("")
        self.groupBox1.setFlat(True)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tfradioButton1 = QtWidgets.QRadioButton(self.groupBox1)
        self.tfradioButton1.setChecked(True)
        self.tfradioButton1.setObjectName("tfradioButton1")
        self.gridLayout_13.addWidget(self.tfradioButton1, 0, 0, 1, 1)
        self.ssradioButton1 = QtWidgets.QRadioButton(self.groupBox1)
        self.ssradioButton1.setObjectName("ssradioButton1")
        self.gridLayout_13.addWidget(self.ssradioButton1, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox1, 0, 1, 1, 1)
        self.principalTab.addTab(self.analisisTab, "")
        self.PIDTab = QtWidgets.QWidget()
        self.PIDTab.setObjectName("PIDTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.PIDTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.kpHSlider2 = QtWidgets.QSlider(self.PIDTab)
        self.kpHSlider2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kpHSlider2.sizePolicy().hasHeightForWidth())
        self.kpHSlider2.setSizePolicy(sizePolicy)
        self.kpHSlider2.setMaximum(1000)
        self.kpHSlider2.setSingleStep(1)
        self.kpHSlider2.setProperty("value", 1)
        self.kpHSlider2.setTracking(True)
        self.kpHSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.kpHSlider2.setInvertedAppearance(False)
        self.kpHSlider2.setInvertedControls(False)
        self.kpHSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.kpHSlider2.setTickInterval(10)
        self.kpHSlider2.setObjectName("kpHSlider2")
        self.gridLayout_8.addWidget(self.kpHSlider2, 8, 2, 1, 1)
        self.kiHSlider2 = QtWidgets.QSlider(self.PIDTab)
        self.kiHSlider2.setEnabled(False)
        self.kiHSlider2.setMaximum(1000)
        self.kiHSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.kiHSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.kiHSlider2.setTickInterval(10)
        self.kiHSlider2.setObjectName("kiHSlider2")
        self.gridLayout_8.addWidget(self.kiHSlider2, 9, 2, 1, 1)
        self.kdHSlider2 = QtWidgets.QSlider(self.PIDTab)
        self.kdHSlider2.setEnabled(False)
        self.kdHSlider2.setMaximum(200)
        self.kdHSlider2.setSliderPosition(0)
        self.kdHSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.kdHSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.kdHSlider2.setTickInterval(2)
        self.kdHSlider2.setObjectName("kdHSlider2")
        self.gridLayout_8.addWidget(self.kdHSlider2, 10, 2, 1, 1)
        self.kiCheckBox2 = QtWidgets.QCheckBox(self.PIDTab)
        self.kiCheckBox2.setTristate(False)
        self.kiCheckBox2.setObjectName("kiCheckBox2")
        self.gridLayout_8.addWidget(self.kiCheckBox2, 9, 3, 1, 1)
        self.kpCheckBox2 = QtWidgets.QCheckBox(self.PIDTab)
        self.kpCheckBox2.setChecked(True)
        self.kpCheckBox2.setObjectName("kpCheckBox2")
        self.gridLayout_8.addWidget(self.kpCheckBox2, 8, 3, 1, 1)
        self.kdCheckBox2 = QtWidgets.QCheckBox(self.PIDTab)
        self.kdCheckBox2.setObjectName("kdCheckBox2")
        self.gridLayout_8.addWidget(self.kdCheckBox2, 10, 3, 1, 1)
        self.stepGraphicsView2 = QtWidgets.QGraphicsView(self.PIDTab)
        self.stepGraphicsView2.setObjectName("stepGraphicsView2")
        self.gridLayout_8.addWidget(self.stepGraphicsView2, 0, 2, 8, 2)
        self.PIDstackedWidget = QtWidgets.QStackedWidget(self.PIDTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PIDstackedWidget.sizePolicy().hasHeightForWidth())
        self.PIDstackedWidget.setSizePolicy(sizePolicy)
        self.PIDstackedWidget.setObjectName("PIDstackedWidget")
        self.tf1 = QtWidgets.QWidget()
        self.tf1.setObjectName("tf1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tf1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.datosLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datosLabel2.sizePolicy().hasHeightForWidth())
        self.datosLabel2.setSizePolicy(sizePolicy)
        self.datosLabel2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.datosLabel2.setScaledContents(False)
        self.datosLabel2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.datosLabel2.setWordWrap(False)
        self.datosLabel2.setObjectName("datosLabel2")
        self.gridLayout_10.addWidget(self.datosLabel2, 4, 0, 1, 1)
        self.demLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demLabel2.sizePolicy().hasHeightForWidth())
        self.demLabel2.setSizePolicy(sizePolicy)
        self.demLabel2.setObjectName("demLabel2")
        self.gridLayout_10.addWidget(self.demLabel2, 2, 0, 1, 1)
        self.numLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLabel2.sizePolicy().hasHeightForWidth())
        self.numLabel2.setSizePolicy(sizePolicy)
        self.numLabel2.setObjectName("numLabel2")
        self.gridLayout_10.addWidget(self.numLabel2, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 6, 1, 1, 1)
        self.tfcalcButton2 = QtWidgets.QPushButton(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfcalcButton2.sizePolicy().hasHeightForWidth())
        self.tfcalcButton2.setSizePolicy(sizePolicy)
        self.tfcalcButton2.setObjectName("tfcalcButton2")
        self.gridLayout_10.addWidget(self.tfcalcButton2, 5, 1, 1, 1)
        self.datosTextEdit2 = QtWidgets.QPlainTextEdit(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datosTextEdit2.sizePolicy().hasHeightForWidth())
        self.datosTextEdit2.setSizePolicy(sizePolicy)
        self.datosTextEdit2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datosTextEdit2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.datosTextEdit2.setReadOnly(True)
        self.datosTextEdit2.setPlainText("")
        self.datosTextEdit2.setBackgroundVisible(True)
        self.datosTextEdit2.setObjectName("datosTextEdit2")
        self.gridLayout_10.addWidget(self.datosTextEdit2, 4, 1, 1, 1)
        self.coefLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coefLabel2.sizePolicy().hasHeightForWidth())
        self.coefLabel2.setSizePolicy(sizePolicy)
        self.coefLabel2.setObjectName("coefLabel2")
        self.gridLayout_10.addWidget(self.coefLabel2, 0, 0, 1, 2)
        self.demEdit2 = QtWidgets.QLineEdit(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demEdit2.sizePolicy().hasHeightForWidth())
        self.demEdit2.setSizePolicy(sizePolicy)
        self.demEdit2.setObjectName("demEdit2")
        self.gridLayout_10.addWidget(self.demEdit2, 2, 1, 1, 1)
        self.numEdit2 = QtWidgets.QLineEdit(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numEdit2.sizePolicy().hasHeightForWidth())
        self.numEdit2.setSizePolicy(sizePolicy)
        self.numEdit2.setObjectName("numEdit2")
        self.gridLayout_10.addWidget(self.numEdit2, 1, 1, 1, 1)
        self.tfperiodoEdit2 = QtWidgets.QLineEdit(self.tf1)
        self.tfperiodoEdit2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfperiodoEdit2.sizePolicy().hasHeightForWidth())
        self.tfperiodoEdit2.setSizePolicy(sizePolicy)
        self.tfperiodoEdit2.setObjectName("tfperiodoEdit2")
        self.gridLayout_10.addWidget(self.tfperiodoEdit2, 3, 1, 1, 1)
        self.tfdiscretocheckBox2 = QtWidgets.QCheckBox(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdiscretocheckBox2.sizePolicy().hasHeightForWidth())
        self.tfdiscretocheckBox2.setSizePolicy(sizePolicy)
        self.tfdiscretocheckBox2.setObjectName("tfdiscretocheckBox2")
        self.gridLayout_10.addWidget(self.tfdiscretocheckBox2, 3, 0, 1, 1)
        self.PIDstackedWidget.addWidget(self.tf1)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ssLabel1_2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssLabel1_2.sizePolicy().hasHeightForWidth())
        self.ssLabel1_2.setSizePolicy(sizePolicy)
        self.ssLabel1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssLabel1_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssLabel1_2.setWordWrap(False)
        self.ssLabel1_2.setObjectName("ssLabel1_2")
        self.gridLayout_12.addWidget(self.ssLabel1_2, 0, 0, 1, 2)
        self.ssALabel2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssALabel2.sizePolicy().hasHeightForWidth())
        self.ssALabel2.setSizePolicy(sizePolicy)
        self.ssALabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssALabel2.setObjectName("ssALabel2")
        self.gridLayout_12.addWidget(self.ssALabel2, 1, 0, 1, 1)
        self.ssAEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssAEdit2.sizePolicy().hasHeightForWidth())
        self.ssAEdit2.setSizePolicy(sizePolicy)
        self.ssAEdit2.setObjectName("ssAEdit2")
        self.gridLayout_12.addWidget(self.ssAEdit2, 1, 1, 1, 1)
        self.ssBLabel2 = QtWidgets.QLabel(self.page_4)
        self.ssBLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssBLabel2.setObjectName("ssBLabel2")
        self.gridLayout_12.addWidget(self.ssBLabel2, 2, 0, 1, 1)
        self.ssBEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssBEdit2.sizePolicy().hasHeightForWidth())
        self.ssBEdit2.setSizePolicy(sizePolicy)
        self.ssBEdit2.setObjectName("ssBEdit2")
        self.gridLayout_12.addWidget(self.ssBEdit2, 2, 1, 1, 1)
        self.ssCLabel2 = QtWidgets.QLabel(self.page_4)
        self.ssCLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssCLabel2.setObjectName("ssCLabel2")
        self.gridLayout_12.addWidget(self.ssCLabel2, 3, 0, 1, 1)
        self.ssCEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssCEdit2.sizePolicy().hasHeightForWidth())
        self.ssCEdit2.setSizePolicy(sizePolicy)
        self.ssCEdit2.setObjectName("ssCEdit2")
        self.gridLayout_12.addWidget(self.ssCEdit2, 3, 1, 1, 1)
        self.ssDLabel2 = QtWidgets.QLabel(self.page_4)
        self.ssDLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssDLabel2.setObjectName("ssDLabel2")
        self.gridLayout_12.addWidget(self.ssDLabel2, 4, 0, 1, 1)
        self.ssDEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssDEdit2.sizePolicy().hasHeightForWidth())
        self.ssDEdit2.setSizePolicy(sizePolicy)
        self.ssDEdit2.setObjectName("ssDEdit2")
        self.gridLayout_12.addWidget(self.ssDEdit2, 4, 1, 1, 1)
        self.ssdiscretocheckBox1_2 = QtWidgets.QCheckBox(self.page_4)
        self.ssdiscretocheckBox1_2.setObjectName("ssdiscretocheckBox1_2")
        self.gridLayout_12.addWidget(self.ssdiscretocheckBox1_2, 5, 0, 1, 1)
        self.ssperiodoEdit1_2 = QtWidgets.QLineEdit(self.page_4)
        self.ssperiodoEdit1_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssperiodoEdit1_2.sizePolicy().hasHeightForWidth())
        self.ssperiodoEdit1_2.setSizePolicy(sizePolicy)
        self.ssperiodoEdit1_2.setInputMask("")
        self.ssperiodoEdit1_2.setText("")
        self.ssperiodoEdit1_2.setObjectName("ssperiodoEdit1_2")
        self.gridLayout_12.addWidget(self.ssperiodoEdit1_2, 5, 1, 1, 1)
        self.ssdatosLabel1_2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosLabel1_2.sizePolicy().hasHeightForWidth())
        self.ssdatosLabel1_2.setSizePolicy(sizePolicy)
        self.ssdatosLabel1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssdatosLabel1_2.setScaledContents(False)
        self.ssdatosLabel1_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssdatosLabel1_2.setWordWrap(False)
        self.ssdatosLabel1_2.setObjectName("ssdatosLabel1_2")
        self.gridLayout_12.addWidget(self.ssdatosLabel1_2, 6, 0, 1, 1)
        self.ssdatosTextEdit1_2 = QtWidgets.QPlainTextEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosTextEdit1_2.sizePolicy().hasHeightForWidth())
        self.ssdatosTextEdit1_2.setSizePolicy(sizePolicy)
        self.ssdatosTextEdit1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ssdatosTextEdit1_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ssdatosTextEdit1_2.setReadOnly(True)
        self.ssdatosTextEdit1_2.setPlainText("")
        self.ssdatosTextEdit1_2.setBackgroundVisible(True)
        self.ssdatosTextEdit1_2.setObjectName("ssdatosTextEdit1_2")
        self.gridLayout_12.addWidget(self.ssdatosTextEdit1_2, 6, 1, 1, 1)
        self.sscalcButton1_2 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sscalcButton1_2.sizePolicy().hasHeightForWidth())
        self.sscalcButton1_2.setSizePolicy(sizePolicy)
        self.sscalcButton1_2.setObjectName("sscalcButton1_2")
        self.gridLayout_12.addWidget(self.sscalcButton1_2, 7, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem3, 8, 1, 1, 1)
        self.PIDstackedWidget.addWidget(self.page_4)
        self.gridLayout_8.addWidget(self.PIDstackedWidget, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.PIDTab)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tfradioButton2 = QtWidgets.QRadioButton(self.groupBox)
        self.tfradioButton2.setChecked(True)
        self.tfradioButton2.setObjectName("tfradioButton2")
        self.gridLayout_14.addWidget(self.tfradioButton2, 0, 0, 1, 1)
        self.ssradioButton2 = QtWidgets.QRadioButton(self.groupBox)
        self.ssradioButton2.setObjectName("ssradioButton2")
        self.gridLayout_14.addWidget(self.ssradioButton2, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.principalTab.addTab(self.PIDTab, "")
        self.fuzzyTab = QtWidgets.QWidget()
        self.fuzzyTab.setObjectName("fuzzyTab")
        self.principalTab.addTab(self.fuzzyTab, "")
        self.controlSimulacion = QtWidgets.QWidget()
        self.controlSimulacion.setObjectName("controlSimulacion")
        self.principalTab.addTab(self.controlSimulacion, "")
        self.gridLayout.addWidget(self.principalTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionpelado = QtWidgets.QAction(MainWindow)
        self.actionpelado.setObjectName("actionpelado")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        self.principalTab.setCurrentIndex(0)
        self.AnalisisstackedWidget.setCurrentIndex(0)
        self.analisisGraficaTab.setCurrentIndex(0)
        self.PIDstackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.kiCheckBox2, QtCore.SIGNAL("clicked(bool)"), self.kiHSlider2.setEnabled)
        QtCore.QObject.connect(self.kpCheckBox2, QtCore.SIGNAL("clicked(bool)"), self.kpHSlider2.setEnabled)
        QtCore.QObject.connect(self.kdCheckBox2, QtCore.SIGNAL("clicked(bool)"), self.kdHSlider2.setEnabled)
        QtCore.QObject.connect(self.tfdiscretocheckBox1, QtCore.SIGNAL("clicked(bool)"), self.tfperiodoEdit1.setEnabled)
        QtCore.QObject.connect(self.tfdiscretocheckBox2, QtCore.SIGNAL("clicked(bool)"), self.tfperiodoEdit2.setEnabled)
        QtCore.QObject.connect(self.ssdiscretocheckBox1, QtCore.SIGNAL("clicked(bool)"), self.ssperiodoEdit1.setEnabled)
        QtCore.QObject.connect(self.ssdiscretocheckBox1_2, QtCore.SIGNAL("clicked(bool)"), self.ssperiodoEdit1_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.principalTab, self.analisisGraficaTab)
        MainWindow.setTabOrder(self.analisisGraficaTab, self.stepGraphicsView1)
        MainWindow.setTabOrder(self.stepGraphicsView1, self.impulseGraphicsView1)
        MainWindow.setTabOrder(self.impulseGraphicsView1, self.BodeGraphicsView1)
        MainWindow.setTabOrder(self.BodeGraphicsView1, self.NyquistGraphicsView1)
        MainWindow.setTabOrder(self.NyquistGraphicsView1, self.rlocusGraphicsView1)
        MainWindow.setTabOrder(self.rlocusGraphicsView1, self.stepGraphicsView2)
        MainWindow.setTabOrder(self.stepGraphicsView2, self.kpHSlider2)
        MainWindow.setTabOrder(self.kpHSlider2, self.kpCheckBox2)
        MainWindow.setTabOrder(self.kpCheckBox2, self.kiHSlider2)
        MainWindow.setTabOrder(self.kiHSlider2, self.kiCheckBox2)
        MainWindow.setTabOrder(self.kiCheckBox2, self.kdHSlider2)
        MainWindow.setTabOrder(self.kdHSlider2, self.kdCheckBox2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Laboratorio de sistemas de control", None, -1))
        self.tfLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "Coeficientes de la funcion de transferencia", None, -1))
        self.tfcalcButton1.setText(QtWidgets.QApplication.translate("MainWindow", "Calcular", None, -1))
        self.demLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "Denominador", None, -1))
        self.numLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "Numerador", None, -1))
        self.tfdatosLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "Datos", None, -1))
        self.tfnumEdit1.setText(QtWidgets.QApplication.translate("MainWindow", "[1]", None, -1))
        self.tfdemEdit1.setText(QtWidgets.QApplication.translate("MainWindow", "[1, 1, 1]", None, -1))
        self.tfperiodoEdit1.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Periodo de muestreo", None, -1))
        self.tfdiscretocheckBox1.setText(QtWidgets.QApplication.translate("MainWindow", "Discreto", None, -1))
        self.ssALabel1.setText(QtWidgets.QApplication.translate("MainWindow", "A", None, -1))
        self.ssAEdit1.setText(QtWidgets.QApplication.translate("MainWindow", "[ [-1, -1], [1,  0] ]", None, -1))
        self.ssBLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "B", None, -1))
        self.ssBEdit1.setText(QtWidgets.QApplication.translate("MainWindow", "[ [1], [0] ]", None, -1))
        self.sscalcButton1.setText(QtWidgets.QApplication.translate("MainWindow", "Calcular", None, -1))
        self.ssdatosLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "Datos", None, -1))
        self.ssLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "Matrices de estado", None, -1))
        self.ssperiodoEdit1.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Periodo de muestreo", None, -1))
        self.ssdiscretocheckBox1.setText(QtWidgets.QApplication.translate("MainWindow", "Discreto", None, -1))
        self.ssCEdit1.setText(QtWidgets.QApplication.translate("MainWindow", "[ [0, 1] ]", None, -1))
        self.ssDEdit1.setText(QtWidgets.QApplication.translate("MainWindow", "[ [0] ]", None, -1))
        self.ssCLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.ssDLabel1.setText(QtWidgets.QApplication.translate("MainWindow", "D", None, -1))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.stepTab), QtWidgets.QApplication.translate("MainWindow", "Step", None, -1))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.impulseTab), QtWidgets.QApplication.translate("MainWindow", "Impulso", None, -1))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.bodeTab), QtWidgets.QApplication.translate("MainWindow", "Bode", None, -1))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.nyquistTab), QtWidgets.QApplication.translate("MainWindow", "Nyquist", None, -1))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.rlocusTab), QtWidgets.QApplication.translate("MainWindow", "root locus", None, -1))
        self.tfradioButton1.setText(QtWidgets.QApplication.translate("MainWindow", "TF", None, -1))
        self.ssradioButton1.setText(QtWidgets.QApplication.translate("MainWindow", "SS", None, -1))
        self.principalTab.setTabText(self.principalTab.indexOf(self.analisisTab), QtWidgets.QApplication.translate("MainWindow", "Analisis", None, -1))
        self.kiCheckBox2.setText(QtWidgets.QApplication.translate("MainWindow", "Ki", None, -1))
        self.kpCheckBox2.setText(QtWidgets.QApplication.translate("MainWindow", "Kp", None, -1))
        self.kdCheckBox2.setText(QtWidgets.QApplication.translate("MainWindow", "Kd", None, -1))
        self.datosLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "Datos", None, -1))
        self.demLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "Denominador", None, -1))
        self.numLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "Numerador", None, -1))
        self.tfcalcButton2.setText(QtWidgets.QApplication.translate("MainWindow", "Calcular", None, -1))
        self.coefLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "Coeficientes de la funcion de transferencia", None, -1))
        self.demEdit2.setText(QtWidgets.QApplication.translate("MainWindow", "[1, 1, 1]", None, -1))
        self.numEdit2.setText(QtWidgets.QApplication.translate("MainWindow", "[1]", None, -1))
        self.tfdiscretocheckBox2.setText(QtWidgets.QApplication.translate("MainWindow", "Discreto", None, -1))
        self.ssLabel1_2.setText(QtWidgets.QApplication.translate("MainWindow", "Matrices de estado", None, -1))
        self.ssALabel2.setText(QtWidgets.QApplication.translate("MainWindow", "A", None, -1))
        self.ssAEdit2.setText(QtWidgets.QApplication.translate("MainWindow", "[1]", None, -1))
        self.ssBLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "B", None, -1))
        self.ssBEdit2.setText(QtWidgets.QApplication.translate("MainWindow", "[1, 1, 1]", None, -1))
        self.ssCLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.ssDLabel2.setText(QtWidgets.QApplication.translate("MainWindow", "D", None, -1))
        self.ssdiscretocheckBox1_2.setText(QtWidgets.QApplication.translate("MainWindow", "Discreto", None, -1))
        self.ssperiodoEdit1_2.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Periodo de muestreo", None, -1))
        self.ssdatosLabel1_2.setText(QtWidgets.QApplication.translate("MainWindow", "Datos", None, -1))
        self.sscalcButton1_2.setText(QtWidgets.QApplication.translate("MainWindow", "Calcular", None, -1))
        self.tfradioButton2.setText(QtWidgets.QApplication.translate("MainWindow", "TF", None, -1))
        self.ssradioButton2.setText(QtWidgets.QApplication.translate("MainWindow", "SS", None, -1))
        self.principalTab.setTabText(self.principalTab.indexOf(self.PIDTab), QtWidgets.QApplication.translate("MainWindow", "PID Tuning", None, -1))
        self.principalTab.setTabText(self.principalTab.indexOf(self.fuzzyTab), QtWidgets.QApplication.translate("MainWindow", "Logica difusa", None, -1))
        self.principalTab.setTabText(self.principalTab.indexOf(self.controlSimulacion), QtWidgets.QApplication.translate("MainWindow", "Simulacion", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionpelado.setText(QtWidgets.QApplication.translate("MainWindow", "pelado", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

from mlpwidget import MlpWidget, MlpWidgetSubplot

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

