# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(900, 711)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.principalTab = QtWidgets.QTabWidget(self.centralwidget)
        self.principalTab.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.principalTab.setPalette(palette)
        self.principalTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.principalTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.principalTab.setElideMode(QtCore.Qt.ElideNone)
        self.principalTab.setDocumentMode(True)
        self.principalTab.setTabsClosable(False)
        self.principalTab.setTabBarAutoHide(True)
        self.principalTab.setObjectName("principalTab")
        self.analisisTab = QtWidgets.QWidget()
        self.analisisTab.setObjectName("analisisTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.analisisTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AnalisisstackedWidget = QtWidgets.QStackedWidget(self.analisisTab)
        self.AnalisisstackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnalisisstackedWidget.sizePolicy().hasHeightForWidth())
        self.AnalisisstackedWidget.setSizePolicy(sizePolicy)
        self.AnalisisstackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AnalisisstackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AnalisisstackedWidget.setObjectName("AnalisisstackedWidget")
        self.tf = QtWidgets.QWidget()
        self.tf.setObjectName("tf")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tf)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tfdemEdit1 = QtWidgets.QLineEdit(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdemEdit1.sizePolicy().hasHeightForWidth())
        self.tfdemEdit1.setSizePolicy(sizePolicy)
        self.tfdemEdit1.setObjectName("tfdemEdit1")
        self.gridLayout_9.addWidget(self.tfdemEdit1, 3, 1, 1, 1)
        self.tfLabel1 = QtWidgets.QLabel(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfLabel1.sizePolicy().hasHeightForWidth())
        self.tfLabel1.setSizePolicy(sizePolicy)
        self.tfLabel1.setObjectName("tfLabel1")
        self.gridLayout_9.addWidget(self.tfLabel1, 1, 0, 1, 2)
        self.tfnumEdit1 = QtWidgets.QLineEdit(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfnumEdit1.sizePolicy().hasHeightForWidth())
        self.tfnumEdit1.setSizePolicy(sizePolicy)
        self.tfnumEdit1.setObjectName("tfnumEdit1")
        self.gridLayout_9.addWidget(self.tfnumEdit1, 2, 1, 1, 1)
        self.tfcalcButton1 = QtWidgets.QPushButton(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfcalcButton1.sizePolicy().hasHeightForWidth())
        self.tfcalcButton1.setSizePolicy(sizePolicy)
        self.tfcalcButton1.setObjectName("tfcalcButton1")
        self.gridLayout_9.addWidget(self.tfcalcButton1, 9, 0, 1, 1)
        self.tfdatosLabel1 = QtWidgets.QLabel(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdatosLabel1.sizePolicy().hasHeightForWidth())
        self.tfdatosLabel1.setSizePolicy(sizePolicy)
        self.tfdatosLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tfdatosLabel1.setScaledContents(False)
        self.tfdatosLabel1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tfdatosLabel1.setWordWrap(False)
        self.tfdatosLabel1.setObjectName("tfdatosLabel1")
        self.gridLayout_9.addWidget(self.tfdatosLabel1, 6, 0, 1, 2)
        self.tfperiodoEdit1 = QtWidgets.QLineEdit(self.tf)
        self.tfperiodoEdit1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfperiodoEdit1.sizePolicy().hasHeightForWidth())
        self.tfperiodoEdit1.setSizePolicy(sizePolicy)
        self.tfperiodoEdit1.setInputMask("")
        self.tfperiodoEdit1.setText("")
        self.tfperiodoEdit1.setObjectName("tfperiodoEdit1")
        self.gridLayout_9.addWidget(self.tfperiodoEdit1, 4, 1, 1, 1)
        self.tfdatosTextEdit1 = QtWidgets.QPlainTextEdit(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdatosTextEdit1.sizePolicy().hasHeightForWidth())
        self.tfdatosTextEdit1.setSizePolicy(sizePolicy)
        self.tfdatosTextEdit1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tfdatosTextEdit1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tfdatosTextEdit1.setReadOnly(True)
        self.tfdatosTextEdit1.setPlainText("")
        self.tfdatosTextEdit1.setBackgroundVisible(True)
        self.tfdatosTextEdit1.setObjectName("tfdatosTextEdit1")
        self.gridLayout_9.addWidget(self.tfdatosTextEdit1, 8, 0, 1, 2)
        self.demLabel1 = QtWidgets.QLabel(self.tf)
        self.demLabel1.setObjectName("demLabel1")
        self.gridLayout_9.addWidget(self.demLabel1, 3, 0, 1, 1)
        self.numLabel1 = QtWidgets.QLabel(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLabel1.sizePolicy().hasHeightForWidth())
        self.numLabel1.setSizePolicy(sizePolicy)
        self.numLabel1.setObjectName("numLabel1")
        self.gridLayout_9.addWidget(self.numLabel1, 2, 0, 1, 1)
        self.tfdiscretocheckBox1 = QtWidgets.QCheckBox(self.tf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdiscretocheckBox1.sizePolicy().hasHeightForWidth())
        self.tfdiscretocheckBox1.setSizePolicy(sizePolicy)
        self.tfdiscretocheckBox1.setObjectName("tfdiscretocheckBox1")
        self.gridLayout_9.addWidget(self.tfdiscretocheckBox1, 4, 0, 1, 1)
        self.tfcomboBox1 = QtWidgets.QComboBox(self.tf)
        self.tfcomboBox1.setEnabled(False)
        self.tfcomboBox1.setEditable(False)
        self.tfcomboBox1.setCurrentText("zoh")
        self.tfcomboBox1.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.tfcomboBox1.setDuplicatesEnabled(True)
        self.tfcomboBox1.setFrame(True)
        self.tfcomboBox1.setObjectName("tfcomboBox1")
        self.tfcomboBox1.addItem("")
        self.tfcomboBox1.setItemText(0, "zoh")
        self.tfcomboBox1.addItem("")
        self.tfcomboBox1.setItemText(1, "foh")
        self.tfcomboBox1.addItem("")
        self.tfcomboBox1.setItemText(2, "backward_diff")
        self.tfcomboBox1.addItem("")
        self.tfcomboBox1.setItemText(3, "euler")
        self.tfcomboBox1.addItem("")
        self.tfcomboBox1.setItemText(4, "tustin")
        self.tfcomboBox1.addItem("")
        self.tfcomboBox1.setItemText(5, "matched")
        self.tfcomboBox1.addItem("")
        self.tfcomboBox1.setItemText(6, "impulse")
        self.gridLayout_9.addWidget(self.tfcomboBox1, 5, 1, 1, 1)
        self.tfMetodoLabel1 = QtWidgets.QLabel(self.tf)
        self.tfMetodoLabel1.setObjectName("tfMetodoLabel1")
        self.gridLayout_9.addWidget(self.tfMetodoLabel1, 5, 0, 1, 1)
        self.AnalisisstackedWidget.addWidget(self.tf)
        self.ss = QtWidgets.QWidget()
        self.ss.setObjectName("ss")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.ss)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.ssCLabel1 = QtWidgets.QLabel(self.ss)
        self.ssCLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssCLabel1.setObjectName("ssCLabel1")
        self.gridLayout_11.addWidget(self.ssCLabel1, 3, 0, 1, 1)
        self.ssperiodoEdit1 = QtWidgets.QLineEdit(self.ss)
        self.ssperiodoEdit1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssperiodoEdit1.sizePolicy().hasHeightForWidth())
        self.ssperiodoEdit1.setSizePolicy(sizePolicy)
        self.ssperiodoEdit1.setInputMask("")
        self.ssperiodoEdit1.setText("")
        self.ssperiodoEdit1.setObjectName("ssperiodoEdit1")
        self.gridLayout_11.addWidget(self.ssperiodoEdit1, 5, 1, 1, 1)
        self.ssBEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssBEdit1.sizePolicy().hasHeightForWidth())
        self.ssBEdit1.setSizePolicy(sizePolicy)
        self.ssBEdit1.setObjectName("ssBEdit1")
        self.gridLayout_11.addWidget(self.ssBEdit1, 2, 1, 1, 1)
        self.ssCEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssCEdit1.sizePolicy().hasHeightForWidth())
        self.ssCEdit1.setSizePolicy(sizePolicy)
        self.ssCEdit1.setObjectName("ssCEdit1")
        self.gridLayout_11.addWidget(self.ssCEdit1, 3, 1, 1, 1)
        self.ssBLabel1 = QtWidgets.QLabel(self.ss)
        self.ssBLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssBLabel1.setObjectName("ssBLabel1")
        self.gridLayout_11.addWidget(self.ssBLabel1, 2, 0, 1, 1)
        self.ssdatosLabel1 = QtWidgets.QLabel(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosLabel1.sizePolicy().hasHeightForWidth())
        self.ssdatosLabel1.setSizePolicy(sizePolicy)
        self.ssdatosLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssdatosLabel1.setScaledContents(False)
        self.ssdatosLabel1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssdatosLabel1.setWordWrap(False)
        self.ssdatosLabel1.setObjectName("ssdatosLabel1")
        self.gridLayout_11.addWidget(self.ssdatosLabel1, 7, 0, 1, 2)
        self.ssAEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssAEdit1.sizePolicy().hasHeightForWidth())
        self.ssAEdit1.setSizePolicy(sizePolicy)
        self.ssAEdit1.setObjectName("ssAEdit1")
        self.gridLayout_11.addWidget(self.ssAEdit1, 1, 1, 1, 1)
        self.ssDEdit1 = QtWidgets.QLineEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssDEdit1.sizePolicy().hasHeightForWidth())
        self.ssDEdit1.setSizePolicy(sizePolicy)
        self.ssDEdit1.setObjectName("ssDEdit1")
        self.gridLayout_11.addWidget(self.ssDEdit1, 4, 1, 1, 1)
        self.ssDLabel1 = QtWidgets.QLabel(self.ss)
        self.ssDLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssDLabel1.setObjectName("ssDLabel1")
        self.gridLayout_11.addWidget(self.ssDLabel1, 4, 0, 1, 1)
        self.sscalcButton1 = QtWidgets.QPushButton(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sscalcButton1.sizePolicy().hasHeightForWidth())
        self.sscalcButton1.setSizePolicy(sizePolicy)
        self.sscalcButton1.setObjectName("sscalcButton1")
        self.gridLayout_11.addWidget(self.sscalcButton1, 10, 0, 1, 1)
        self.ssALabel1 = QtWidgets.QLabel(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssALabel1.sizePolicy().hasHeightForWidth())
        self.ssALabel1.setSizePolicy(sizePolicy)
        self.ssALabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.ssALabel1.setObjectName("ssALabel1")
        self.gridLayout_11.addWidget(self.ssALabel1, 1, 0, 1, 1)
        self.ssdiscretocheckBox1 = QtWidgets.QCheckBox(self.ss)
        self.ssdiscretocheckBox1.setObjectName("ssdiscretocheckBox1")
        self.gridLayout_11.addWidget(self.ssdiscretocheckBox1, 5, 0, 1, 1)
        self.ssLabel1 = QtWidgets.QLabel(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssLabel1.sizePolicy().hasHeightForWidth())
        self.ssLabel1.setSizePolicy(sizePolicy)
        self.ssLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssLabel1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssLabel1.setWordWrap(False)
        self.ssLabel1.setObjectName("ssLabel1")
        self.gridLayout_11.addWidget(self.ssLabel1, 0, 0, 1, 2)
        self.ssdatosTextEdit1 = QtWidgets.QPlainTextEdit(self.ss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosTextEdit1.sizePolicy().hasHeightForWidth())
        self.ssdatosTextEdit1.setSizePolicy(sizePolicy)
        self.ssdatosTextEdit1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ssdatosTextEdit1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ssdatosTextEdit1.setReadOnly(True)
        self.ssdatosTextEdit1.setPlainText("")
        self.ssdatosTextEdit1.setBackgroundVisible(True)
        self.ssdatosTextEdit1.setObjectName("ssdatosTextEdit1")
        self.gridLayout_11.addWidget(self.ssdatosTextEdit1, 8, 0, 1, 2)
        self.sscomboBox1 = QtWidgets.QComboBox(self.ss)
        self.sscomboBox1.setEnabled(False)
        self.sscomboBox1.setCurrentText("zoh")
        self.sscomboBox1.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.sscomboBox1.setDuplicatesEnabled(True)
        self.sscomboBox1.setObjectName("sscomboBox1")
        self.sscomboBox1.addItem("")
        self.sscomboBox1.setItemText(0, "zoh")
        self.sscomboBox1.addItem("")
        self.sscomboBox1.addItem("")
        self.sscomboBox1.addItem("")
        self.sscomboBox1.addItem("")
        self.sscomboBox1.setItemText(4, "tustin")
        self.sscomboBox1.addItem("")
        self.sscomboBox1.setItemText(5, "impulse")
        self.gridLayout_11.addWidget(self.sscomboBox1, 6, 1, 1, 1)
        self.ssMetodoLabel1 = QtWidgets.QLabel(self.ss)
        self.ssMetodoLabel1.setObjectName("ssMetodoLabel1")
        self.gridLayout_11.addWidget(self.ssMetodoLabel1, 6, 0, 1, 1)
        self.AnalisisstackedWidget.addWidget(self.ss)
        self.gridLayout_3.addWidget(self.AnalisisstackedWidget, 1, 1, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.analisisTab)
        self.groupBox1.setTitle("")
        self.groupBox1.setFlat(True)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tfradioButton1 = QtWidgets.QRadioButton(self.groupBox1)
        self.tfradioButton1.setChecked(True)
        self.tfradioButton1.setObjectName("tfradioButton1")
        self.gridLayout_13.addWidget(self.tfradioButton1, 0, 0, 1, 1)
        self.ssradioButton1 = QtWidgets.QRadioButton(self.groupBox1)
        self.ssradioButton1.setObjectName("ssradioButton1")
        self.gridLayout_13.addWidget(self.ssradioButton1, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox1, 0, 1, 1, 1)
        self.analisisGraficaTab = QtWidgets.QTabWidget(self.analisisTab)
        self.analisisGraficaTab.setAutoFillBackground(True)
        self.analisisGraficaTab.setDocumentMode(False)
        self.analisisGraficaTab.setMovable(True)
        self.analisisGraficaTab.setTabBarAutoHide(False)
        self.analisisGraficaTab.setObjectName("analisisGraficaTab")
        self.stepTab = QtWidgets.QWidget()
        self.stepTab.setObjectName("stepTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stepTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stepGraphicsView1 = MlpWidget(self.stepTab)
        self.stepGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stepGraphicsView1.setInteractive(True)
        self.stepGraphicsView1.setObjectName("stepGraphicsView1")
        self.gridLayout_2.addWidget(self.stepGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.stepTab, "")
        self.impulseTab = QtWidgets.QWidget()
        self.impulseTab.setObjectName("impulseTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.impulseTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.impulseGraphicsView1 = MlpWidget(self.impulseTab)
        self.impulseGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.impulseGraphicsView1.setObjectName("impulseGraphicsView1")
        self.gridLayout_4.addWidget(self.impulseGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.impulseTab, "")
        self.bodeTab = QtWidgets.QWidget()
        self.bodeTab.setObjectName("bodeTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bodeTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.BodeGraphicsView1 = MlpWidgetSubplot(self.bodeTab)
        self.BodeGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BodeGraphicsView1.setObjectName("BodeGraphicsView1")
        self.gridLayout_5.addWidget(self.BodeGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.bodeTab, "")
        self.nyquistTab = QtWidgets.QWidget()
        self.nyquistTab.setObjectName("nyquistTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.nyquistTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.NyquistGraphicsView1 = MlpWidget(self.nyquistTab)
        self.NyquistGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.NyquistGraphicsView1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NyquistGraphicsView1.setObjectName("NyquistGraphicsView1")
        self.gridLayout_6.addWidget(self.NyquistGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.nyquistTab, "")
        self.rlocusTab = QtWidgets.QWidget()
        self.rlocusTab.setObjectName("rlocusTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.rlocusTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.rlocusGraphicsView1 = MlpWidget(self.rlocusTab)
        self.rlocusGraphicsView1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rlocusGraphicsView1.setObjectName("rlocusGraphicsView1")
        self.gridLayout_7.addWidget(self.rlocusGraphicsView1, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.rlocusTab, "")
        self.gridLayout_3.addWidget(self.analisisGraficaTab, 0, 3, 8, 1)
        self.principalTab.addTab(self.analisisTab, "")
        self.PIDTab = QtWidgets.QWidget()
        self.PIDTab.setObjectName("PIDTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.PIDTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.PIDstackedWidget = QtWidgets.QStackedWidget(self.PIDTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PIDstackedWidget.sizePolicy().hasHeightForWidth())
        self.PIDstackedWidget.setSizePolicy(sizePolicy)
        self.PIDstackedWidget.setObjectName("PIDstackedWidget")
        self.tf1 = QtWidgets.QWidget()
        self.tf1.setObjectName("tf1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tf1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.demLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demLabel2.sizePolicy().hasHeightForWidth())
        self.demLabel2.setSizePolicy(sizePolicy)
        self.demLabel2.setObjectName("demLabel2")
        self.gridLayout_10.addWidget(self.demLabel2, 2, 0, 1, 1)
        self.tfnumEdit2 = QtWidgets.QLineEdit(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfnumEdit2.sizePolicy().hasHeightForWidth())
        self.tfnumEdit2.setSizePolicy(sizePolicy)
        self.tfnumEdit2.setObjectName("tfnumEdit2")
        self.gridLayout_10.addWidget(self.tfnumEdit2, 1, 1, 1, 1)
        self.numLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLabel2.sizePolicy().hasHeightForWidth())
        self.numLabel2.setSizePolicy(sizePolicy)
        self.numLabel2.setObjectName("numLabel2")
        self.gridLayout_10.addWidget(self.numLabel2, 1, 0, 1, 1)
        self.coefLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coefLabel2.sizePolicy().hasHeightForWidth())
        self.coefLabel2.setSizePolicy(sizePolicy)
        self.coefLabel2.setObjectName("coefLabel2")
        self.gridLayout_10.addWidget(self.coefLabel2, 0, 0, 1, 2)
        self.tfcalcButton2 = QtWidgets.QPushButton(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfcalcButton2.sizePolicy().hasHeightForWidth())
        self.tfcalcButton2.setSizePolicy(sizePolicy)
        self.tfcalcButton2.setObjectName("tfcalcButton2")
        self.gridLayout_10.addWidget(self.tfcalcButton2, 7, 0, 1, 1)
        self.tfdemEdit2 = QtWidgets.QLineEdit(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdemEdit2.sizePolicy().hasHeightForWidth())
        self.tfdemEdit2.setSizePolicy(sizePolicy)
        self.tfdemEdit2.setObjectName("tfdemEdit2")
        self.gridLayout_10.addWidget(self.tfdemEdit2, 2, 1, 1, 1)
        self.tfperiodoEdit2 = QtWidgets.QLineEdit(self.tf1)
        self.tfperiodoEdit2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfperiodoEdit2.sizePolicy().hasHeightForWidth())
        self.tfperiodoEdit2.setSizePolicy(sizePolicy)
        self.tfperiodoEdit2.setObjectName("tfperiodoEdit2")
        self.gridLayout_10.addWidget(self.tfperiodoEdit2, 3, 1, 1, 1)
        self.tfdatosLabel2 = QtWidgets.QLabel(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdatosLabel2.sizePolicy().hasHeightForWidth())
        self.tfdatosLabel2.setSizePolicy(sizePolicy)
        self.tfdatosLabel2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tfdatosLabel2.setScaledContents(False)
        self.tfdatosLabel2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.tfdatosLabel2.setWordWrap(False)
        self.tfdatosLabel2.setObjectName("tfdatosLabel2")
        self.gridLayout_10.addWidget(self.tfdatosLabel2, 5, 0, 1, 2)
        self.tfdiscretocheckBox2 = QtWidgets.QCheckBox(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdiscretocheckBox2.sizePolicy().hasHeightForWidth())
        self.tfdiscretocheckBox2.setSizePolicy(sizePolicy)
        self.tfdiscretocheckBox2.setObjectName("tfdiscretocheckBox2")
        self.gridLayout_10.addWidget(self.tfdiscretocheckBox2, 3, 0, 1, 1)
        self.tfdatosTextEdit2 = QtWidgets.QPlainTextEdit(self.tf1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfdatosTextEdit2.sizePolicy().hasHeightForWidth())
        self.tfdatosTextEdit2.setSizePolicy(sizePolicy)
        self.tfdatosTextEdit2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tfdatosTextEdit2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tfdatosTextEdit2.setReadOnly(True)
        self.tfdatosTextEdit2.setPlainText("")
        self.tfdatosTextEdit2.setBackgroundVisible(True)
        self.tfdatosTextEdit2.setObjectName("tfdatosTextEdit2")
        self.gridLayout_10.addWidget(self.tfdatosTextEdit2, 6, 0, 1, 2)
        self.tfcomboBox2 = QtWidgets.QComboBox(self.tf1)
        self.tfcomboBox2.setEnabled(False)
        self.tfcomboBox2.setCurrentText("zoh")
        self.tfcomboBox2.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.tfcomboBox2.setDuplicatesEnabled(True)
        self.tfcomboBox2.setObjectName("tfcomboBox2")
        self.tfcomboBox2.addItem("")
        self.tfcomboBox2.setItemText(0, "zoh")
        self.tfcomboBox2.addItem("")
        self.tfcomboBox2.setItemText(1, "foh")
        self.tfcomboBox2.addItem("")
        self.tfcomboBox2.setItemText(2, "backward_diff")
        self.tfcomboBox2.addItem("")
        self.tfcomboBox2.setItemText(3, "euler")
        self.tfcomboBox2.addItem("")
        self.tfcomboBox2.setItemText(4, "tustin")
        self.tfcomboBox2.addItem("")
        self.tfcomboBox2.setItemText(5, "matched")
        self.tfcomboBox2.addItem("")
        self.tfcomboBox2.setItemText(6, "impulse")
        self.gridLayout_10.addWidget(self.tfcomboBox2, 4, 1, 1, 1)
        self.tfMetodoLabel2 = QtWidgets.QLabel(self.tf1)
        self.tfMetodoLabel2.setEnabled(True)
        self.tfMetodoLabel2.setObjectName("tfMetodoLabel2")
        self.gridLayout_10.addWidget(self.tfMetodoLabel2, 4, 0, 1, 1)
        self.PIDstackedWidget.addWidget(self.tf1)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ssALabel2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssALabel2.sizePolicy().hasHeightForWidth())
        self.ssALabel2.setSizePolicy(sizePolicy)
        self.ssALabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssALabel2.setObjectName("ssALabel2")
        self.gridLayout_12.addWidget(self.ssALabel2, 1, 0, 1, 1)
        self.ssCLabel2 = QtWidgets.QLabel(self.page_4)
        self.ssCLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssCLabel2.setObjectName("ssCLabel2")
        self.gridLayout_12.addWidget(self.ssCLabel2, 3, 0, 1, 1)
        self.ssDLabel2 = QtWidgets.QLabel(self.page_4)
        self.ssDLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssDLabel2.setObjectName("ssDLabel2")
        self.gridLayout_12.addWidget(self.ssDLabel2, 4, 0, 1, 1)
        self.ssAEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssAEdit2.sizePolicy().hasHeightForWidth())
        self.ssAEdit2.setSizePolicy(sizePolicy)
        self.ssAEdit2.setObjectName("ssAEdit2")
        self.gridLayout_12.addWidget(self.ssAEdit2, 1, 1, 1, 1)
        self.ssperiodoEdit2 = QtWidgets.QLineEdit(self.page_4)
        self.ssperiodoEdit2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssperiodoEdit2.sizePolicy().hasHeightForWidth())
        self.ssperiodoEdit2.setSizePolicy(sizePolicy)
        self.ssperiodoEdit2.setInputMask("")
        self.ssperiodoEdit2.setText("")
        self.ssperiodoEdit2.setObjectName("ssperiodoEdit2")
        self.gridLayout_12.addWidget(self.ssperiodoEdit2, 5, 1, 1, 1)
        self.ssdatosLabel2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosLabel2.sizePolicy().hasHeightForWidth())
        self.ssdatosLabel2.setSizePolicy(sizePolicy)
        self.ssdatosLabel2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssdatosLabel2.setScaledContents(False)
        self.ssdatosLabel2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssdatosLabel2.setWordWrap(False)
        self.ssdatosLabel2.setObjectName("ssdatosLabel2")
        self.gridLayout_12.addWidget(self.ssdatosLabel2, 7, 0, 1, 2)
        self.sscalcButton2 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sscalcButton2.sizePolicy().hasHeightForWidth())
        self.sscalcButton2.setSizePolicy(sizePolicy)
        self.sscalcButton2.setObjectName("sscalcButton2")
        self.gridLayout_12.addWidget(self.sscalcButton2, 9, 0, 1, 1)
        self.ssBLabel2 = QtWidgets.QLabel(self.page_4)
        self.ssBLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.ssBLabel2.setObjectName("ssBLabel2")
        self.gridLayout_12.addWidget(self.ssBLabel2, 2, 0, 1, 1)
        self.ssLabel1_2 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssLabel1_2.sizePolicy().hasHeightForWidth())
        self.ssLabel1_2.setSizePolicy(sizePolicy)
        self.ssLabel1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ssLabel1_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ssLabel1_2.setWordWrap(False)
        self.ssLabel1_2.setObjectName("ssLabel1_2")
        self.gridLayout_12.addWidget(self.ssLabel1_2, 0, 0, 1, 2)
        self.ssCEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssCEdit2.sizePolicy().hasHeightForWidth())
        self.ssCEdit2.setSizePolicy(sizePolicy)
        self.ssCEdit2.setObjectName("ssCEdit2")
        self.gridLayout_12.addWidget(self.ssCEdit2, 3, 1, 1, 1)
        self.ssDEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssDEdit2.sizePolicy().hasHeightForWidth())
        self.ssDEdit2.setSizePolicy(sizePolicy)
        self.ssDEdit2.setObjectName("ssDEdit2")
        self.gridLayout_12.addWidget(self.ssDEdit2, 4, 1, 1, 1)
        self.ssdatosTextEdit2 = QtWidgets.QPlainTextEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssdatosTextEdit2.sizePolicy().hasHeightForWidth())
        self.ssdatosTextEdit2.setSizePolicy(sizePolicy)
        self.ssdatosTextEdit2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ssdatosTextEdit2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ssdatosTextEdit2.setReadOnly(True)
        self.ssdatosTextEdit2.setPlainText("")
        self.ssdatosTextEdit2.setBackgroundVisible(True)
        self.ssdatosTextEdit2.setObjectName("ssdatosTextEdit2")
        self.gridLayout_12.addWidget(self.ssdatosTextEdit2, 8, 0, 1, 2)
        self.ssdiscretocheckBox2 = QtWidgets.QCheckBox(self.page_4)
        self.ssdiscretocheckBox2.setObjectName("ssdiscretocheckBox2")
        self.gridLayout_12.addWidget(self.ssdiscretocheckBox2, 5, 0, 1, 1)
        self.ssBEdit2 = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssBEdit2.sizePolicy().hasHeightForWidth())
        self.ssBEdit2.setSizePolicy(sizePolicy)
        self.ssBEdit2.setObjectName("ssBEdit2")
        self.gridLayout_12.addWidget(self.ssBEdit2, 2, 1, 1, 1)
        self.sscomboBox2 = QtWidgets.QComboBox(self.page_4)
        self.sscomboBox2.setEnabled(False)
        self.sscomboBox2.setCurrentText("zoh")
        self.sscomboBox2.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.sscomboBox2.setDuplicatesEnabled(True)
        self.sscomboBox2.setObjectName("sscomboBox2")
        self.sscomboBox2.addItem("")
        self.sscomboBox2.setItemText(0, "zoh")
        self.sscomboBox2.addItem("")
        self.sscomboBox2.addItem("")
        self.sscomboBox2.addItem("")
        self.sscomboBox2.addItem("")
        self.sscomboBox2.setItemText(4, "tustin")
        self.sscomboBox2.addItem("")
        self.sscomboBox2.setItemText(5, "impulse")
        self.gridLayout_12.addWidget(self.sscomboBox2, 6, 1, 1, 1)
        self.ssMetodoLabel2 = QtWidgets.QLabel(self.page_4)
        self.ssMetodoLabel2.setObjectName("ssMetodoLabel2")
        self.gridLayout_12.addWidget(self.ssMetodoLabel2, 6, 0, 1, 1)
        self.PIDstackedWidget.addWidget(self.page_4)
        self.gridLayout_8.addWidget(self.PIDstackedWidget, 1, 0, 5, 1)
        self.groupBox2 = QtWidgets.QGroupBox(self.PIDTab)
        self.groupBox2.setTitle("")
        self.groupBox2.setFlat(True)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tfradioButton2 = QtWidgets.QRadioButton(self.groupBox2)
        self.tfradioButton2.setChecked(True)
        self.tfradioButton2.setObjectName("tfradioButton2")
        self.gridLayout_14.addWidget(self.tfradioButton2, 0, 0, 1, 1)
        self.ssradioButton2 = QtWidgets.QRadioButton(self.groupBox2)
        self.ssradioButton2.setObjectName("ssradioButton2")
        self.gridLayout_14.addWidget(self.ssradioButton2, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox2, 0, 0, 1, 1)
        self.stepGraphicsView2 = MlpWidget(self.PIDTab)
        self.stepGraphicsView2.setObjectName("stepGraphicsView2")
        self.gridLayout_8.addWidget(self.stepGraphicsView2, 0, 2, 8, 2)
        self.kiHSlider2 = QtWidgets.QSlider(self.PIDTab)
        self.kiHSlider2.setEnabled(False)
        self.kiHSlider2.setMaximum(1000)
        self.kiHSlider2.setProperty("value", 20)
        self.kiHSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.kiHSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.kiHSlider2.setTickInterval(10)
        self.kiHSlider2.setObjectName("kiHSlider2")
        self.gridLayout_8.addWidget(self.kiHSlider2, 9, 2, 1, 1)
        self.kiCheckBox2 = QtWidgets.QCheckBox(self.PIDTab)
        self.kiCheckBox2.setTristate(False)
        self.kiCheckBox2.setObjectName("kiCheckBox2")
        self.gridLayout_8.addWidget(self.kiCheckBox2, 9, 3, 1, 1)
        self.kpHSlider2 = QtWidgets.QSlider(self.PIDTab)
        self.kpHSlider2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kpHSlider2.sizePolicy().hasHeightForWidth())
        self.kpHSlider2.setSizePolicy(sizePolicy)
        self.kpHSlider2.setMaximum(1000)
        self.kpHSlider2.setSingleStep(1)
        self.kpHSlider2.setProperty("value", 20)
        self.kpHSlider2.setTracking(True)
        self.kpHSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.kpHSlider2.setInvertedAppearance(False)
        self.kpHSlider2.setInvertedControls(False)
        self.kpHSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.kpHSlider2.setTickInterval(10)
        self.kpHSlider2.setObjectName("kpHSlider2")
        self.gridLayout_8.addWidget(self.kpHSlider2, 8, 2, 1, 1)
        self.kdCheckBox2 = QtWidgets.QCheckBox(self.PIDTab)
        self.kdCheckBox2.setObjectName("kdCheckBox2")
        self.gridLayout_8.addWidget(self.kdCheckBox2, 10, 3, 1, 1)
        self.kpCheckBox2 = QtWidgets.QCheckBox(self.PIDTab)
        self.kpCheckBox2.setChecked(True)
        self.kpCheckBox2.setObjectName("kpCheckBox2")
        self.gridLayout_8.addWidget(self.kpCheckBox2, 8, 3, 1, 1)
        self.kdHSlider2 = QtWidgets.QSlider(self.PIDTab)
        self.kdHSlider2.setEnabled(False)
        self.kdHSlider2.setMaximum(1000)
        self.kdHSlider2.setProperty("value", 10)
        self.kdHSlider2.setSliderPosition(10)
        self.kdHSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.kdHSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.kdHSlider2.setTickInterval(10)
        self.kdHSlider2.setObjectName("kdHSlider2")
        self.gridLayout_8.addWidget(self.kdHSlider2, 10, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kpLabel2 = QtWidgets.QLabel(self.PIDTab)
        self.kpLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kpLabel2.setObjectName("kpLabel2")
        self.horizontalLayout.addWidget(self.kpLabel2)
        self.kpValueLabel2 = QtWidgets.QLabel(self.PIDTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kpValueLabel2.sizePolicy().hasHeightForWidth())
        self.kpValueLabel2.setSizePolicy(sizePolicy)
        self.kpValueLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kpValueLabel2.setObjectName("kpValueLabel2")
        self.horizontalLayout.addWidget(self.kpValueLabel2)
        self.gridLayout_8.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.kiLabel2 = QtWidgets.QLabel(self.PIDTab)
        self.kiLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kiLabel2.setObjectName("kiLabel2")
        self.horizontalLayout_2.addWidget(self.kiLabel2)
        self.kiValueLabel2 = QtWidgets.QLabel(self.PIDTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kiValueLabel2.sizePolicy().hasHeightForWidth())
        self.kiValueLabel2.setSizePolicy(sizePolicy)
        self.kiValueLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kiValueLabel2.setObjectName("kiValueLabel2")
        self.horizontalLayout_2.addWidget(self.kiValueLabel2)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.kdLabel2 = QtWidgets.QLabel(self.PIDTab)
        self.kdLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kdLabel2.setObjectName("kdLabel2")
        self.horizontalLayout_3.addWidget(self.kdLabel2)
        self.kdValueLabel2 = QtWidgets.QLabel(self.PIDTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kdValueLabel2.sizePolicy().hasHeightForWidth())
        self.kdValueLabel2.setSizePolicy(sizePolicy)
        self.kdValueLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kdValueLabel2.setObjectName("kdValueLabel2")
        self.horizontalLayout_3.addWidget(self.kdValueLabel2)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 10, 0, 1, 1)
        self.principalTab.addTab(self.PIDTab, "")
        self.fuzzyTab = QtWidgets.QWidget()
        self.fuzzyTab.setObjectName("fuzzyTab")
        self.principalTab.addTab(self.fuzzyTab, "")
        self.controlSimulacion = QtWidgets.QWidget()
        self.controlSimulacion.setObjectName("controlSimulacion")
        self.principalTab.addTab(self.controlSimulacion, "")
        self.gridLayout.addWidget(self.principalTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionpelado = QtWidgets.QAction(MainWindow)
        self.actionpelado.setObjectName("actionpelado")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        self.principalTab.setCurrentIndex(0)
        self.AnalisisstackedWidget.setCurrentIndex(0)
        self.sscomboBox1.setCurrentIndex(0)
        self.analisisGraficaTab.setCurrentIndex(0)
        self.PIDstackedWidget.setCurrentIndex(0)
        self.kiCheckBox2.clicked['bool'].connect(self.kiHSlider2.setEnabled)
        self.kpCheckBox2.clicked['bool'].connect(self.kpHSlider2.setEnabled)
        self.kdCheckBox2.clicked['bool'].connect(self.kdHSlider2.setEnabled)
        self.tfdiscretocheckBox1.clicked['bool'].connect(self.tfperiodoEdit1.setEnabled)
        self.tfdiscretocheckBox2.clicked['bool'].connect(self.tfperiodoEdit2.setEnabled)
        self.ssdiscretocheckBox1.clicked['bool'].connect(self.ssperiodoEdit1.setEnabled)
        self.ssdiscretocheckBox2.clicked['bool'].connect(self.ssperiodoEdit2.setEnabled)
        self.tfdiscretocheckBox1.clicked['bool'].connect(self.tfcomboBox1.setEnabled)
        self.ssdiscretocheckBox1.clicked['bool'].connect(self.sscomboBox1.setEnabled)
        self.ssdiscretocheckBox2.clicked['bool'].connect(self.sscomboBox2.setEnabled)
        self.tfdiscretocheckBox2.clicked['bool'].connect(self.tfcomboBox2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.analisisGraficaTab, self.stepGraphicsView1)
        MainWindow.setTabOrder(self.stepGraphicsView1, self.impulseGraphicsView1)
        MainWindow.setTabOrder(self.impulseGraphicsView1, self.BodeGraphicsView1)
        MainWindow.setTabOrder(self.BodeGraphicsView1, self.NyquistGraphicsView1)
        MainWindow.setTabOrder(self.NyquistGraphicsView1, self.rlocusGraphicsView1)
        MainWindow.setTabOrder(self.rlocusGraphicsView1, self.stepGraphicsView2)
        MainWindow.setTabOrder(self.stepGraphicsView2, self.kpHSlider2)
        MainWindow.setTabOrder(self.kpHSlider2, self.kpCheckBox2)
        MainWindow.setTabOrder(self.kpCheckBox2, self.kiHSlider2)
        MainWindow.setTabOrder(self.kiHSlider2, self.kiCheckBox2)
        MainWindow.setTabOrder(self.kiCheckBox2, self.kdHSlider2)
        MainWindow.setTabOrder(self.kdHSlider2, self.kdCheckBox2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laboratorio de sistemas de control"))
        self.tfdemEdit1.setText(_translate("MainWindow", "[1, 1, 1]"))
        self.tfLabel1.setText(_translate("MainWindow", "Coeficientes de la funcion de transferencia"))
        self.tfnumEdit1.setText(_translate("MainWindow", "[1]"))
        self.tfcalcButton1.setText(_translate("MainWindow", "Calcular"))
        self.tfdatosLabel1.setText(_translate("MainWindow", "Datos"))
        self.tfperiodoEdit1.setPlaceholderText(_translate("MainWindow", "Periodo de muestreo"))
        self.demLabel1.setText(_translate("MainWindow", "Denominador"))
        self.numLabel1.setText(_translate("MainWindow", "Numerador"))
        self.tfdiscretocheckBox1.setText(_translate("MainWindow", "Discreto"))
        self.tfMetodoLabel1.setText(_translate("MainWindow", "Metodo"))
        self.ssCLabel1.setText(_translate("MainWindow", "C"))
        self.ssperiodoEdit1.setPlaceholderText(_translate("MainWindow", "Periodo de muestreo"))
        self.ssBEdit1.setText(_translate("MainWindow", "[ [1], [0] ]"))
        self.ssCEdit1.setText(_translate("MainWindow", "[ [0, 1] ]"))
        self.ssBLabel1.setText(_translate("MainWindow", "B"))
        self.ssdatosLabel1.setText(_translate("MainWindow", "Datos"))
        self.ssAEdit1.setText(_translate("MainWindow", "[ [-1, -1], [1,  0] ]"))
        self.ssDEdit1.setText(_translate("MainWindow", "[ [0] ]"))
        self.ssDLabel1.setText(_translate("MainWindow", "D"))
        self.sscalcButton1.setText(_translate("MainWindow", "Calcular"))
        self.ssALabel1.setText(_translate("MainWindow", "A"))
        self.ssdiscretocheckBox1.setText(_translate("MainWindow", "Discreto"))
        self.ssLabel1.setText(_translate("MainWindow", "Matrices de estado"))
        self.sscomboBox1.setItemText(1, _translate("MainWindow", "foh"))
        self.sscomboBox1.setItemText(2, _translate("MainWindow", "backward_diff"))
        self.sscomboBox1.setItemText(3, _translate("MainWindow", "euler"))
        self.ssMetodoLabel1.setText(_translate("MainWindow", "Metodo"))
        self.tfradioButton1.setText(_translate("MainWindow", "TF"))
        self.ssradioButton1.setText(_translate("MainWindow", "SS"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.stepTab), _translate("MainWindow", "Step"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.impulseTab), _translate("MainWindow", "Impulso"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.bodeTab), _translate("MainWindow", "Bode"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.nyquistTab), _translate("MainWindow", "Nyquist"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.rlocusTab), _translate("MainWindow", "root locus"))
        self.principalTab.setTabText(self.principalTab.indexOf(self.analisisTab), _translate("MainWindow", "Analisis"))
        self.demLabel2.setText(_translate("MainWindow", "Denominador"))
        self.tfnumEdit2.setText(_translate("MainWindow", "[1]"))
        self.numLabel2.setText(_translate("MainWindow", "Numerador"))
        self.coefLabel2.setText(_translate("MainWindow", "Coeficientes de la funcion de transferencia"))
        self.tfcalcButton2.setText(_translate("MainWindow", "Calcular"))
        self.tfdemEdit2.setText(_translate("MainWindow", "[1, 1, 1]"))
        self.tfperiodoEdit2.setPlaceholderText(_translate("MainWindow", "Periodo de muestreo"))
        self.tfdatosLabel2.setText(_translate("MainWindow", "Datos"))
        self.tfdiscretocheckBox2.setText(_translate("MainWindow", "Discreto"))
        self.tfMetodoLabel2.setText(_translate("MainWindow", "Metodo"))
        self.ssALabel2.setText(_translate("MainWindow", "A"))
        self.ssCLabel2.setText(_translate("MainWindow", "C"))
        self.ssDLabel2.setText(_translate("MainWindow", "D"))
        self.ssAEdit2.setText(_translate("MainWindow", "[ [-1, -1], [1,  0] ]"))
        self.ssperiodoEdit2.setPlaceholderText(_translate("MainWindow", "Periodo de muestreo"))
        self.ssdatosLabel2.setText(_translate("MainWindow", "Datos"))
        self.sscalcButton2.setText(_translate("MainWindow", "Calcular"))
        self.ssBLabel2.setText(_translate("MainWindow", "B"))
        self.ssLabel1_2.setText(_translate("MainWindow", "Matrices de estado"))
        self.ssCEdit2.setText(_translate("MainWindow", "[ [0, 1] ]"))
        self.ssDEdit2.setText(_translate("MainWindow", "[ [0] ]"))
        self.ssdiscretocheckBox2.setText(_translate("MainWindow", "Discreto"))
        self.ssBEdit2.setText(_translate("MainWindow", "[ [1], [0] ]"))
        self.sscomboBox2.setItemText(1, _translate("MainWindow", "foh"))
        self.sscomboBox2.setItemText(2, _translate("MainWindow", "backward_diff"))
        self.sscomboBox2.setItemText(3, _translate("MainWindow", "euler"))
        self.ssMetodoLabel2.setText(_translate("MainWindow", "Metodo"))
        self.tfradioButton2.setText(_translate("MainWindow", "TF"))
        self.ssradioButton2.setText(_translate("MainWindow", "SS"))
        self.kiCheckBox2.setText(_translate("MainWindow", "Ki"))
        self.kdCheckBox2.setText(_translate("MainWindow", "Kd"))
        self.kpCheckBox2.setText(_translate("MainWindow", "Kp"))
        self.kpLabel2.setText(_translate("MainWindow", "Kp:"))
        self.kpValueLabel2.setText(_translate("MainWindow", "1.0"))
        self.kiLabel2.setText(_translate("MainWindow", "Ki"))
        self.kiValueLabel2.setText(_translate("MainWindow", "1.0"))
        self.kdLabel2.setText(_translate("MainWindow", "Kd"))
        self.kdValueLabel2.setText(_translate("MainWindow", "0.2"))
        self.principalTab.setTabText(self.principalTab.indexOf(self.PIDTab), _translate("MainWindow", "PID Tuning"))
        self.principalTab.setTabText(self.principalTab.indexOf(self.fuzzyTab), _translate("MainWindow", "Logica difusa"))
        self.principalTab.setTabText(self.principalTab.indexOf(self.controlSimulacion), _translate("MainWindow", "Simulacion"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionpelado.setText(_translate("MainWindow", "pelado"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from mlpwidget import MlpWidget, MlpWidgetSubplot

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

