# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\PC\Documents\Descargas chrome\NO TOCAR MALDITO IDIOTA!! ZZZZ\kleiver\Tesis\Nueva tesis\LaboratorioDeControl\VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 553)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.principalTab = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.principalTab.setPalette(palette)
        self.principalTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.principalTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.principalTab.setElideMode(QtCore.Qt.ElideNone)
        self.principalTab.setDocumentMode(True)
        self.principalTab.setTabsClosable(False)
        self.principalTab.setTabBarAutoHide(True)
        self.principalTab.setObjectName("principalTab")
        self.analisisTab = QtWidgets.QWidget()
        self.analisisTab.setObjectName("analisisTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.analisisTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.analisisGraficaTab = QtWidgets.QTabWidget(self.analisisTab)
        self.analisisGraficaTab.setAutoFillBackground(True)
        self.analisisGraficaTab.setDocumentMode(False)
        self.analisisGraficaTab.setMovable(True)
        self.analisisGraficaTab.setTabBarAutoHide(False)
        self.analisisGraficaTab.setObjectName("analisisGraficaTab")
        self.stepTab = QtWidgets.QWidget()
        self.stepTab.setObjectName("stepTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stepTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stepGraphicsView = QtWidgets.QGraphicsView(self.stepTab)
        self.stepGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stepGraphicsView.setInteractive(True)
        self.stepGraphicsView.setObjectName("stepGraphicsView")
        self.gridLayout_2.addWidget(self.stepGraphicsView, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.stepTab, "")
        self.impulseTab = QtWidgets.QWidget()
        self.impulseTab.setObjectName("impulseTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.impulseTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.impulseGraphicsView = QtWidgets.QGraphicsView(self.impulseTab)
        self.impulseGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.impulseGraphicsView.setObjectName("impulseGraphicsView")
        self.gridLayout_4.addWidget(self.impulseGraphicsView, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.impulseTab, "")
        self.bodeTab = QtWidgets.QWidget()
        self.bodeTab.setObjectName("bodeTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bodeTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.magBodeGraphicsView = QtWidgets.QGraphicsView(self.bodeTab)
        self.magBodeGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.magBodeGraphicsView.setObjectName("magBodeGraphicsView")
        self.gridLayout_5.addWidget(self.magBodeGraphicsView, 0, 0, 1, 1)
        self.phaBodeGraphicsView = QtWidgets.QGraphicsView(self.bodeTab)
        self.phaBodeGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.phaBodeGraphicsView.setObjectName("phaBodeGraphicsView")
        self.gridLayout_5.addWidget(self.phaBodeGraphicsView, 1, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.bodeTab, "")
        self.nyquistTab = QtWidgets.QWidget()
        self.nyquistTab.setObjectName("nyquistTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.nyquistTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.NyquistGraphicsView = QtWidgets.QGraphicsView(self.nyquistTab)
        self.NyquistGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.NyquistGraphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NyquistGraphicsView.setObjectName("NyquistGraphicsView")
        self.gridLayout_6.addWidget(self.NyquistGraphicsView, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.nyquistTab, "")
        self.rlocusTab = QtWidgets.QWidget()
        self.rlocusTab.setObjectName("rlocusTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.rlocusTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.rlocusGraphicsView = QtWidgets.QGraphicsView(self.rlocusTab)
        self.rlocusGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rlocusGraphicsView.setObjectName("rlocusGraphicsView")
        self.gridLayout_7.addWidget(self.rlocusGraphicsView, 0, 0, 1, 1)
        self.analisisGraficaTab.addTab(self.rlocusTab, "")
        self.gridLayout_3.addWidget(self.analisisGraficaTab, 0, 2, 8, 1)
        self.coefLabel1 = QtWidgets.QLabel(self.analisisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coefLabel1.sizePolicy().hasHeightForWidth())
        self.coefLabel1.setSizePolicy(sizePolicy)
        self.coefLabel1.setObjectName("coefLabel1")
        self.gridLayout_3.addWidget(self.coefLabel1, 1, 0, 1, 2)
        self.numLabel1 = QtWidgets.QLabel(self.analisisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numLabel1.sizePolicy().hasHeightForWidth())
        self.numLabel1.setSizePolicy(sizePolicy)
        self.numLabel1.setObjectName("numLabel1")
        self.gridLayout_3.addWidget(self.numLabel1, 2, 0, 1, 1)
        self.numEdit1 = QtWidgets.QLineEdit(self.analisisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numEdit1.sizePolicy().hasHeightForWidth())
        self.numEdit1.setSizePolicy(sizePolicy)
        self.numEdit1.setObjectName("numEdit1")
        self.gridLayout_3.addWidget(self.numEdit1, 2, 1, 1, 1)
        self.demLabel1 = QtWidgets.QLabel(self.analisisTab)
        self.demLabel1.setObjectName("demLabel1")
        self.gridLayout_3.addWidget(self.demLabel1, 3, 0, 1, 1)
        self.demEdit1 = QtWidgets.QLineEdit(self.analisisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demEdit1.sizePolicy().hasHeightForWidth())
        self.demEdit1.setSizePolicy(sizePolicy)
        self.demEdit1.setObjectName("demEdit1")
        self.gridLayout_3.addWidget(self.demEdit1, 3, 1, 1, 1)
        self.calcButton1 = QtWidgets.QPushButton(self.analisisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcButton1.sizePolicy().hasHeightForWidth())
        self.calcButton1.setSizePolicy(sizePolicy)
        self.calcButton1.setObjectName("calcButton1")
        self.gridLayout_3.addWidget(self.calcButton1, 4, 1, 1, 1)
        self.datosTextEdit1 = QtWidgets.QPlainTextEdit(self.analisisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datosTextEdit1.sizePolicy().hasHeightForWidth())
        self.datosTextEdit1.setSizePolicy(sizePolicy)
        self.datosTextEdit1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datosTextEdit1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.datosTextEdit1.setReadOnly(True)
        self.datosTextEdit1.setPlainText("")
        self.datosTextEdit1.setBackgroundVisible(True)
        self.datosTextEdit1.setObjectName("datosTextEdit1")
        self.gridLayout_3.addWidget(self.datosTextEdit1, 5, 1, 1, 1)
        self.datosLabel1 = QtWidgets.QLabel(self.analisisTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datosLabel1.sizePolicy().hasHeightForWidth())
        self.datosLabel1.setSizePolicy(sizePolicy)
        self.datosLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.datosLabel1.setScaledContents(False)
        self.datosLabel1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.datosLabel1.setWordWrap(False)
        self.datosLabel1.setObjectName("datosLabel1")
        self.gridLayout_3.addWidget(self.datosLabel1, 5, 0, 1, 1)
        self.principalTab.addTab(self.analisisTab, "")
        self.PIDTab = QtWidgets.QWidget()
        self.PIDTab.setObjectName("PIDTab")
        self.principalTab.addTab(self.PIDTab, "")
        self.gridLayout.addWidget(self.principalTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionpelado = QtWidgets.QAction(MainWindow)
        self.actionpelado.setObjectName("actionpelado")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        self.principalTab.setCurrentIndex(0)
        self.analisisGraficaTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.stepTab), _translate("MainWindow", "Step"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.impulseTab), _translate("MainWindow", "Impulso"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.bodeTab), _translate("MainWindow", "Bode"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.nyquistTab), _translate("MainWindow", "Nyquist"))
        self.analisisGraficaTab.setTabText(self.analisisGraficaTab.indexOf(self.rlocusTab), _translate("MainWindow", "root locus"))
        self.coefLabel1.setText(_translate("MainWindow", "Coeficientes de la funcion de transferencia"))
        self.numLabel1.setText(_translate("MainWindow", "Numerador"))
        self.numEdit1.setText(_translate("MainWindow", "[1]"))
        self.demLabel1.setText(_translate("MainWindow", "Denominador"))
        self.demEdit1.setText(_translate("MainWindow", "[1, 1, 1]"))
        self.calcButton1.setText(_translate("MainWindow", "Calcular"))
        self.datosLabel1.setText(_translate("MainWindow", "Datos"))
        self.principalTab.setTabText(self.principalTab.indexOf(self.analisisTab), _translate("MainWindow", "Analisis"))
        self.principalTab.setTabText(self.principalTab.indexOf(self.PIDTab), _translate("MainWindow", "PID Tuning"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionpelado.setText(_translate("MainWindow", "pelado"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

